In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=['i am a good boy',
      'your videos are good',
      'i am the smarter than others',
      'the hail of naredra modi'
      ]

In [4]:
sent

['i am a good boy',
 'your videos are good',
 'i am the smarter than others',
 'the hail of naredra modi']

In [5]:
#define vocab size
voc_size=10000

In [6]:
#one hot represenntation 
one_hot_repr=[one_hot(words,voc_size) for words in sent ]

In [7]:
one_hot_repr

[[7021, 9219, 4724, 7326, 6412],
 [2195, 3663, 7982, 7326],
 [7021, 9219, 1845, 9928, 8784, 5257],
 [1845, 8955, 1389, 8267, 7030]]

In [8]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
#set some sentace lenghth for the equuilize the sentace length


In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)


In [11]:
print(embedded_docs)

[[   0    0    0 7021 9219 4724 7326 6412]
 [   0    0    0    0 2195 3663 7982 7326]
 [   0    0 7021 9219 1845 9928 8784 5257]
 [   0    0    0 1845 8955 1389 8267 7030]]


In [12]:
#feature representaion 
dim=10

In [16]:
#model
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

e:\New_folder\RNN project\rnn_env\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
#model summary
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
#prerdiction
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step


array([[[-7.2058924e-03, -4.8985053e-02, -5.0403178e-05, -2.0053113e-02,
          3.4534130e-02,  4.6868909e-02,  7.2723255e-03, -4.2010020e-02,
         -1.6637482e-02,  3.6520425e-02],
        [-7.2058924e-03, -4.8985053e-02, -5.0403178e-05, -2.0053113e-02,
          3.4534130e-02,  4.6868909e-02,  7.2723255e-03, -4.2010020e-02,
         -1.6637482e-02,  3.6520425e-02],
        [-7.2058924e-03, -4.8985053e-02, -5.0403178e-05, -2.0053113e-02,
          3.4534130e-02,  4.6868909e-02,  7.2723255e-03, -4.2010020e-02,
         -1.6637482e-02,  3.6520425e-02],
        [ 3.8173571e-03,  2.8273169e-02,  3.7592601e-02, -5.4263696e-03,
          4.7744885e-03, -1.1423446e-02, -1.2133382e-02, -4.5193698e-02,
         -4.8203778e-02,  8.2302094e-03],
        [-3.8385294e-02,  3.1431165e-02,  4.3255750e-02,  3.8360622e-02,
         -8.9851990e-03,  9.0025291e-03,  1.3727296e-02,  2.7798302e-03,
         -4.1107081e-02, -3.1760681e-02],
        [-4.9473096e-02,  1.4189307e-02,  3.3796798e-02, -2.

In [19]:
#this shoes the representation of the each docs